#!/usr/bin/env python3

import threading
import time


counter = 0


def worker1():
    global counter
    while True:
        counter += 1
        counter -= 1


def worker2():
    global counter
    while True:
        counter += 1
        counter -= 1


def printer():
    global counter
    while True:
        print(f"{counter=}")
        time.sleep(1)


threading.Thread(target=worker1).start()
threading.Thread(target=worker2).start()
threading.Thread(target=printer).start()
