#!/usr/bin/env python3


"""
Note that this will run fine with latest Python3 (e.g. 3.10) Running with
earlier versions (e.g. Python 3.6.8 or Python2), the counter will keep
fluctuating as worker1 and worker2's access to the shared variable counter is
not synchronized
"""


import threading
import time


counter = 0


def worker1():
    global counter
    while True:
        counter += 1
        counter -= 1


def worker2():
    global counter
    while True:
        counter += 1
        counter -= 1


def printer():
    global counter
    while True:
        print(f"{counter=}")
        time.sleep(1)


threading.Thread(target=worker1).start()
threading.Thread(target=worker2).start()
threading.Thread(target=printer).start()
