#!/usr/bin/env python3


"""
Ref: https://leetcode.com/problems/palindrome-number/

Given an integer x, return true if x is a palindrome and false otherwise.


Example 1:

Input: x = 121
Output: true
Explanation: 121 reads as 121 from left to right and from right to left.


Example 2:

Input: x = -121
Output: false
Explanation: From left to right, it reads -121. From right to left, it becomes 121-. Therefore it is not a palindrome.



Example 3:

Input: x = 10
Output: false
Explanation: Reads 01 from right to left. Therefore it is not a palindrome.


Constraints:

-2^31 <= x <= 2^31 - 1


Follow up: Could you solve it without converting the integer to a string?
"""


class Solution:
    def is_palindrome(self, x: int) -> bool:
        if x < 0:
            return False

        digits = []
        while x > 0:
            x, d = divmod(x, 10)
            digits.append(d)

        for i in range(len(digits)//2):
            if digits[i] != digits[-1-i]:
                return False

        return True

    def is_palindrome_using_string(self, x: int) -> bool:
        if x < 0:
            return False

        int_str = str(x)
        int_str_reserved = int_str[::-1]

        return int_str == int_str_reserved


def main():
    assert Solution().is_palindrome(0)
    assert Solution().is_palindrome(1)
    assert Solution().is_palindrome(11)
    assert Solution().is_palindrome(121)
    assert Solution().is_palindrome(1221)
    assert Solution().is_palindrome(12321)
    assert Solution().is_palindrome(123321)

    assert not Solution().is_palindrome(-1)
    assert not Solution().is_palindrome(-121)
    assert not Solution().is_palindrome(-1221)
    assert not Solution().is_palindrome(-12321)
    assert not Solution().is_palindrome(-123321)

    assert not Solution().is_palindrome(12)
    assert not Solution().is_palindrome(123)
    assert not Solution().is_palindrome(123456)
    assert not Solution().is_palindrome(12112211)
    assert not Solution().is_palindrome(12218989)
    assert not Solution().is_palindrome(123219911)
    assert not Solution().is_palindrome(12332181282)


main()
