#!/usr/bin/env python3


"""
Ref: https://leetcode.com/problems/longest-common-prefix

Write a function to find the longest common prefix string amongst an array of
strings.

If there is no common prefix, return an empty string "".


Example 1:

Input: strs = ["flower", "flow", "flight"]
Output: "fl"


Example 2:

Input: strs = ["dog", "racecar", "car"]
Output: ""
Explanation: There is no common prefix among the input strings.


Constraints:

1 <= strs.length <= 200
0 <= strs[i].length <= 200
strs[i] consists of only lowercase English letters.
"""


from typing import List


class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        prefix = ""
        # max prefix can be at most as the minimum length word in the given list
        max_prefix_length = min([len(s) for s in strs])

        for i in range(max_prefix_length):
            c = strs[0][i]
            for s in strs:
                if s[i] != c:
                    return prefix
            prefix += c

        return prefix


def main():
    assert Solution().longestCommonPrefix(["flower", "flow", "flight"]) == "fl"
    assert Solution().longestCommonPrefix(["dog", "racecar", "car"]) == ""


main()
