#!/usr/bin/env python3


"""
Ref: https://leetcode.com/problems/ransom-note

Ransom Note

Given two strings ransomNote and magazine, return true if ransomNote can be
constructed by using the letters from magazine and false otherwise.

Each letter in magazine can only be used once in ransomNote.


Example 1:

Input: ransomNote = "a", magazine = "b"
Output: false


Example 2:

Input: ransomNote = "aa", magazine = "ab"
Output: false


Example 3:

Input: ransomNote = "aa", magazine = "aab"
Output: true


Constraints:

1 <= ransomNote.length, magazine.length <= 10^5
ransomNote and magazine consist of lowercase English letters.
"""


from collections import Counter


class Solution:
    def canConstruct(self, ransomNote: str, magazine: str) -> bool:
        r = Counter(ransomNote)
        total_matched = 0
        len_note = len(ransomNote)
        for c in magazine:
            if r[c] > 0:
                r[c] -= 1
                total_matched += 1
                if total_matched == len_note:
                    return True

        return False


def main():
    assert not Solution().canConstruct("a", "b")
    assert not Solution().canConstruct("aa", "bb")
    assert Solution().canConstruct("aa", "aab")


main()
