#!/usr/bin/env python3


"""
Ref: https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii

Given an integer array nums sorted in non-decreasing order, remove some
duplicates in-place such that each unique element appears at most twice. The
relative order of the elements should be kept the same.

Since it is impossible to change the length of the array in some languages, you
must instead have the result be placed in the first part of the array nums. More
formally, if there are k elements after removing the duplicates, then the first
k elements of nums should hold the final result. It does not matter what you
leave beyond the first k elements.

Return k after placing the final result in the first k slots of nums.

Do not allocate extra space for another array. You must do this by modifying the
input array in-place with O(1) extra memory.


Example 1:

Input: nums = [1,1,1,2,2,3]
Output: 5, nums = [1,1,2,2,3,_]
Explanation: Your function should return k = 5, with the first five elements of
nums being 1, 1, 2, 2 and 3 respectively. It does not matter what you leave
beyond the returned k (hence they are underscores).


Example 2:

Input: nums = [0,0,1,1,1,1,2,3,3]
Output: 7, nums = [0,0,1,1,2,3,3,_,_]
Explanation: Your function should return k = 7, with the first seven elements of
nums being 0, 0, 1, 1, 2, 3 and 3 respectively. It does not matter what you
leave beyond the returned k (hence they are underscores).


Constraints:

1 <= nums.length <= 3 * 10^4
-10^4 <= nums[i] <= 10^4
nums is sorted in non-decreasing order.
"""


from typing import List


class Solution:
    def removeDuplicates(self, nums: List[int]) -> int:
        return self.remove_duplicates(nums, max_repeats_allowed=2)

    def remove_duplicates(self, nums: List[int], max_repeats_allowed=2) -> int:
        i = 0
        j = 1
        seen_count = 1
        while j < len(nums):
            if nums[i] != nums[j]:
                i += 1
                nums[i] = nums[j]
                seen_count = 1
            elif seen_count < max_repeats_allowed:
                i += 1
                nums[i] = nums[j]
                seen_count += 1

            j += 1

        return i+1


def main():
    nums = [1, 1, 1, 1, 1, 1, 1]
    assert Solution().removeDuplicates(nums) == 2
    assert nums[:2] == [1, 1]

    nums = [1, 1, 1, 2, 2, 3]
    assert Solution().removeDuplicates(nums) == 5
    assert nums[:5] == [1, 1, 2, 2, 3]

    nums = [0, 0, 1, 1, 1, 1, 2, 3, 3]
    assert Solution().removeDuplicates(nums) == 7
    assert nums[:7] == [0, 0, 1, 1, 2, 3, 3]

    nums = [1, 1, 1, 1, 1, 1, 1]
    assert Solution().remove_duplicates(nums, max_repeats_allowed=3) == 3
    assert nums[:3] == [1, 1, 1]

    nums = [1, 1, 1, 2, 2, 3]
    assert Solution().remove_duplicates(nums, max_repeats_allowed=3) == 6
    assert nums[:6] == [1, 1, 1, 2, 2, 3]

    nums = [0, 0, 1, 1, 1, 1, 2, 3, 3]
    assert Solution().remove_duplicates(nums, max_repeats_allowed=3) == 8
    assert nums[:8] == [0, 0, 1, 1, 1, 2, 3, 3]

    nums = [1, 1, 1, 1, 1, 1, 1]
    assert Solution().remove_duplicates(nums, max_repeats_allowed=1) == 1
    assert nums[:1] == [1]

    nums = [1, 1, 1, 2, 2, 3]
    assert Solution().remove_duplicates(nums, max_repeats_allowed=1) == 3
    assert nums[:3] == [1, 2, 3]

    nums = [0, 0, 1, 1, 1, 1, 2, 3, 3]
    assert Solution().remove_duplicates(nums, max_repeats_allowed=1) == 4
    assert nums[:4] == [0, 1, 2, 3]


main()
