#!/usr/bin/env python3


"""Random password generator"""


import random
import sys


DEFAULT_PASSWORD_LENGTH = 20


def generate_strong_password():
    """Generates and prints a random password of given length"""
    password_length = int(sys.argv[1]) if len(
        sys.argv) > 1 else DEFAULT_PASSWORD_LENGTH
    ascii_letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    digits = '0123456789'
    punctuation = '!#$%&()*+,-./:;<=>?@[]^_{|}~'
    printable = digits + ascii_letters + punctuation

    print("".join(random.choices(printable, k=password_length)))


generate_strong_password()
